# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' A specialized matrix multiplication
#' @description A specialized matrix multiplication function used in person_fit() while calculating the variance of
#' loglikelihodd for cluster items
#' @param m, a numeric matrix
#' @param v, a numeric vector
#' @author Zhongtian Lin lzt713@gmail.com
#' @export
#' @import Rcpp
mmult <- function(m, v) {
    .Call('_MIRTutils_mmult', PACKAGE = 'MIRTutils', m, v)
}

